# Generated by Django 5.2.4 on 2025-07-08 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('cash', 'Cash'), ('credit_card', 'Credit Card'), ('debit_card', 'Debit Card'), ('paypal', 'PayPal'), ('mercado_pago', 'Mercado Pago')], max_length=50, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='client',
            name='payment_methods',
        ),
        migrations.AlterField(
            model_name='professional',
            name='profession',
            field=models.CharField(choices=[('plumber', 'Plumber'), ('electrician', 'Electrician'), ('cleaner', 'Cleaner'), ('gardener', 'Gardener'), ('developer', 'Developer'), ('designer', 'Designer'), ('other', 'Other')], default='other', max_length=100),
        ),
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.CharField(choices=[('plumbing', 'Plumbing'), ('electricity', 'Electricity'), ('cleaning', 'Cleaning'), ('gardening', 'Gardening'), ('technology', 'Technology'), ('other', 'Other')], default='other', max_length=50),
        ),
        migrations.AddField(
            model_name='client',
            name='payment_methods',
            field=models.ManyToManyField(blank=True, to='core.paymentmethod'),
        ),
    ]
